export interface Product {
  id: string;
  name: string;
  category: string;
  subCategory: string;
  price: number;
  originalPrice: number;
  stock: number;
  sku: string;
  description: string;
  image: string;
  status: 'active' | 'inactive' | 'draft';
  createdAt: string;
  updatedAt: string;
  colors?: string[];
  sizes?: string[];
  material?: string;
  tags?: string[];
}

export const PRODUCT_STATUSES = [
  { value: 'active', label: 'Active', color: 'bg-green-100 text-green-800' },
  { value: 'inactive', label: 'Inactive', color: 'bg-gray-100 text-gray-800' },
  { value: 'draft', label: 'Draft', color: 'bg-yellow-100 text-yellow-800' },
];

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Italian Wool Suit',
    category: 'Men',
    subCategory: 'Formal',
    price: 14499,
    originalPrice: 16999,
    stock: 45,
    sku: 'SKU-001',
    description: 'Tailored fit Italian wool suit with premium finishing',
    image: '/products/suit.jpg',
    status: 'active',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-18',
    colors: ['Navy', 'Charcoal', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: '100% Italian Wool',
    tags: ['formal', 'suit', 'wool'],
  },
  {
    id: '2',
    name: 'Cashmere Sweater',
    category: 'Men',
    subCategory: 'Casual',
    price: 450,
    originalPrice: 599,
    stock: 28,
    sku: 'SKU-002',
    description: 'Soft cashmere sweater in charcoal with ribbed finishing',
    image: '/products/sweater.jpg',
    status: 'active',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-18',
    colors: ['Navy', 'Gray', 'Cream'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: '100% Cashmere',
    tags: ['casual', 'sweater', 'cashmere'],
  },
  {
    id: '3',
    name: 'Leather Briefcase',
    category: 'Accessories',
    subCategory: 'Bags',
    price: 899,
    originalPrice: 1099,
    stock: 12,
    sku: 'SKU-003',
    description: 'Full-grain leather briefcase with compartments',
    image: '/products/briefcase.jpg',
    status: 'active',
    createdAt: '2024-01-05',
    updatedAt: '2024-01-18',
    colors: ['Brown', 'Black', 'Tan'],
    sizes: ['One Size'],
    material: 'Full-Grain Leather',
    tags: ['briefcase', 'leather', 'professional'],
  },
  {
    id: '4',
    name: 'Oxford Shoes',
    category: 'Men',
    subCategory: 'Footwear',
    price: 599,
    originalPrice: 799,
    stock: 34,
    sku: 'SKU-004',
    description: 'Handcrafted leather oxford shoes with genuine leather sole',
    image: '/products/shoes.jpg',
    status: 'active',
    createdAt: '2024-01-08',
    updatedAt: '2024-01-18',
    colors: ['Brown', 'Black'],
    sizes: ['6', '7', '8', '9', '10', '11', '12', '13'],
    material: 'Leather',
    tags: ['shoes', 'oxford', 'formal'],
  },
  {
    id: '5',
    name: 'Silk Tie',
    category: 'Men',
    subCategory: 'Accessories',
    price: 120,
    originalPrice: 180,
    stock: 67,
    sku: 'SKU-005',
    description: '100% silk ties with premium finishing',
    image: '/products/tie.jpg',
    status: 'active',
    createdAt: '2024-01-12',
    updatedAt: '2024-01-18',
    colors: ['Navy', 'Burgundy', 'Silver', 'Black'],
    sizes: ['One Size'],
    material: '100% Silk',
    tags: ['tie', 'silk', 'formal'],
  },
  {
    id: '6',
    name: 'Designer Handbag',
    category: 'Women',
    subCategory: 'Bags',
    price: 2499,
    originalPrice: 3299,
    stock: 8,
    sku: 'SKU-006',
    description: 'Premium leather handbag with signature design',
    image: '/products/handbag.jpg',
    status: 'active',
    createdAt: '2024-01-14',
    updatedAt: '2024-01-18',
    colors: ['Black', 'Tan', 'Burgundy'],
    sizes: ['One Size'],
    material: 'Premium Leather',
    tags: ['handbag', 'designer', 'leather'],
  },
  {
    id: '7',
    name: 'Cashmere Scarf',
    category: 'Women',
    subCategory: 'Accessories',
    price: 280,
    originalPrice: 399,
    stock: 19,
    sku: 'SKU-007',
    description: 'Luxurious cashmere scarf with delicate weaving',
    image: '/products/scarf.jpg',
    status: 'active',
    createdAt: '2024-01-09',
    updatedAt: '2024-01-18',
    colors: ['Cream', 'Navy', 'Gray', 'Rose'],
    sizes: ['One Size'],
    material: '100% Cashmere',
    tags: ['scarf', 'cashmere', 'accessories'],
  },
  {
    id: '8',
    name: 'Premium Watch',
    category: 'Accessories',
    subCategory: 'Watches',
    price: 4999,
    originalPrice: 6499,
    stock: 5,
    sku: 'SKU-008',
    description: 'Swiss-made luxury watch with automatic movement',
    image: '/products/watch.jpg',
    status: 'draft',
    createdAt: '2024-01-16',
    updatedAt: '2024-01-18',
    colors: ['Silver', 'Gold', 'Rose Gold'],
    sizes: ['One Size'],
    material: 'Stainless Steel',
    tags: ['watch', 'luxury', 'swiss'],
  },
];
